@startchen
left to right direction
entity Entity_Main{
   attribute
   derived_attribute <<derived>>
   key_attribute <<key>>
   Multi_valued <<multi>>
   composite{
      LName
      FName
   }
entity Weak_Entity <<weak>>{
   key_attribute <<key>>
}

entity Entity {
attribute
}
relationship relation {

}
relationship weak_relation <<identifying>>{

}

weak_relation -1- Entity_Main
weak_relation -1- Weak_Entity
relation -1- Entity_Main
relation =N= Entity
@endchen
